version: "3.8"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: project1
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
